<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.1</Version>
    <!-- Manifest fields (see https://github.com/goatcorp/DalamudPackager/blob/827d88dc/DalamudPackager/DalamudPackager.cs#L420) -->
    <Author>Melon Backflip</Author>
    <Name>Rime Ready Check</Name>
    <Punchline>Wakey Wakey Rime.</Punchline>
    <Description>Changes ready check notification to something more appropriate</Description>
    <Tags>ready check;party</Tags>
    <PackageProjectUrl>https://github.com/Mundayne/rime-plugin</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Sounds\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
